# Jwt
jwt:
  secret: Sh4boyQhalL8OPOeGxMP8nC8PjQmJKth7xnK+bRyg6U=
  ttl: 3600000
  issuer: http://icommerce.com

# Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9090/eureka
  instance:
    preferIpAddress: true