server:
  port: 9091

# Database
spring:
  datasource:
    url: jdbc:h2:mem:user
    driverClassName: org.h2.Driver
    username: sa
    password: pw
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true